import type { Post } from "@/posts/types"

export const post: Post = {
  slug: "hvordan-ki-egentlig-virker",
  title: "Hvordan KI egentlig virker",
  category: "Kunstig intelligens",
  date: "26. september 2025",
  dateISO: "2025-09-26",
  excerpt: "Har du lurt på hvordan NRK TV treffer med neste programforslag, eller hvordan BankID kjenner igjen ansiktet ditt på to sekunder.",
  image: "/posts/hvordan-ki-egentlig-virker/featured.jpg",
  imageAlt: "Hvordan KI egentlig virker",
  contentHtml: `<p>Har du lurt på hvordan NRK TV treffer med neste programforslag, eller hvordan BankID kjenner igjen ansiktet ditt på to sekunder. Det er ikke magi, det er maskinlæring i arbeid. Kunstig intelligens er i ferd med å bli en usynlig infrastruktur i hverdagen, fra kundeservice hos offentlige etater til logistikken hos Posten. Likevel oppleves den ofte som en svart boks. Nettopp derfor er det nyttig å forstå hva som skjer bak kulissene, og hvordan data, algoritmer og trening får maskiner til å lære.</p>
<h2>Hva er kunstig intelligens</h2>
<p>I sin kjerne handler kunstig intelligens om å få maskiner til å etterligne menneskelig problemløsning. Maskinlæring er metoden som gjør dette mulig i praksis. I stedet for at utviklere skriver alle regler på forhånd, lar vi systemet se mange eksempler og trekke ut mønstre selv. Dermed kan det ta beslutninger med høy fart og lav feilrate, som å flagge mistenkelige transaksjoner i en norsk bank eller sortere henvendelser i helsevesenet etter hastegrad. Kunstig intelligens og maskinlæring henger tett sammen, men de er ikke det samme. AI er ambisjonen om smarte systemer, mens maskinlæring er verktøykassen som lar dem bli bedre med erfaring.</p>
<figure><img src="/posts/hvordan-ki-egentlig-virker/1.jpg" alt="Hvordan KI egentlig virker" loading="lazy" /></figure>
<h3>Maskinlæring og dyp læring</h3>
<p>Maskinlæring er motoren som gjør at systemer forbedrer seg når de eksponeres for mer <a href="/trender/riktige-beslutninger-basert-pa-data">data</a>. Modellen justerer interne vekter slik at avstanden mellom gjetning og fasit blir mindre for hver runde. Dyp læring er en spesialisert retning der vi bruker kunstige nevrale nettverk med mange lag for å løse mer komplekse oppgaver. Slike nettverk kan fange opp nyanser som enklere metoder overser, som forskjellen mellom en skade på asfalt og en skygge i et videostrøm fra et norsk veiprosjekt, eller intensjonen i en kundemail hos et forsikringsselskap. For å gjøre sammenhengen enkel: AI er målet, maskinlæring er metoden, og algoritmene er oppskriftene som guider læringen. Poenget er at systemene ikke følger en stiv regelbok, men forbedrer seg med data som erfaring.</p>
<h3>Slik lærer systemene av data</h3>
<p>Tre byggesteiner må på plass: data, algoritmer og trening. Data er drivstoffet. Jo mer presise og varierte eksempler, desto bedre blir modellene. Derfor bruker en aktør som FINN strukturert historikk for å forstå hvilke annonser som bør løftes for hvilke brukere, mens et kollektivselskap som Ruter trenger rike datasett for å forutsi belastning i sanntid. Algoritmene er instruksjonene som styrer hvordan systemet lærer av disse eksemplene. De er statistiske modeller som justerer seg dynamisk, ikke et sett med ufravikelige regler.</p>
<p>Selve treningen er en syklus av å gjette, få tilbakemelding, og justere, ganske likt måten mennesker blir bedre på gjennom øvelse. Likevel kan læringen gå galt. Overtilpasning oppstår når modellen pugger treningsdataene og mister evnen til å generalisere. Undertilpasning oppstår når den ikke har kapasitet til å lære mønstrene i det hele tatt. Derfor bruker team verktøy og teknikker som tidlig stopp, regularisering og hold-out tester for å finne riktig balanse. Det er kjedelig håndverk, men det er her kvaliteten skapes.</p>
<figure><img src="/posts/hvordan-ki-egentlig-virker/2.png" alt="Hvordan KI egentlig virker" loading="lazy" /></figure>
<h2>Slik kommer du i gang</h2>
<p>Det mest effektive er å starte lite og konkret. Velg et problem der du kan måle effekt, som å redusere svartiden på kundeservice eller forbedre rekkefølgen på produkter i en nettbutikk. Python er ofte førstevalget fordi bibliotekene for datahåndtering og modellering er modne og lett tilgjengelige. Samtidig gir JavaScript mulighet til å legge lette modeller direkte i nettleseren.</p>
<p>For virksomheter som ikke ønsker å kode, finnes det gode plattformer som lar deg trene modeller gjennom visuelle grensesnitt, men uansett bør du ha en som eier problemet, en som eier dataene, og en som kan vurdere risiko. I Norge finnes dessuten solide fagmiljøer og <a href="https://www.digdir.no/kunstig-intelligens/ki-ressurser/4145" target="_blank" rel="noopener noreferrer">kurs</a> hos universiteter og bransjeaktører som gjør terskelen lavere. Begynn med en <a href="/trender/prototypingens-rolle-i-webutvikling">prototype</a>, lær, og skaler først når verdien er dokumentert. Slik bygger du kompetanse, ikke bare prosjekter.</p>
<h3>Tre måter maskiner lærer på</h3>
<p>I veiledet læring får modellen eksempler der fasiten er kjent. Tenk på et anti-spam filter i en norsk virksomhet som trenes på eposter merket som ønsket eller uønsket. Modellen lærer hvilke kombinasjoner av ord, avsendere og mønstre som typisk hører til hver kategori, og tar deretter gode valg på nye meldinger. I ikke-veiledet læring finnes ingen fasit, og systemet må selv finne strukturer i data. Det er nyttig når en strømmetjeneste vil gruppere brukere med like preferanser, eller når en handelsaktør ønsker å oppdage uventede segmenter i kjøpsatferd uten å ha definert dem på forhånd. I forsterkningslæring lærer systemet gjennom belønning og prøving og feiling.</p>
<p>Det kan for eksempel brukes i produksjon hos Kongsberg-miljøer for å optimalisere styring i komplekse prosesser. Eller i logistikksimuleringer der en agent lærer å planlegge ruter mer effektivt enn en forhåndsprogrammering klarer. Fellesnevneren er at læringen blir bedre jo tydeligere målet er, jo mer ærlige dataene er, og jo mer disiplinert teamet itererer mellom hypoteser og fakta.</p>
<p>Kunstig intelligens er mindre mystikk enn metode. Når vi ser forbi buzzordene og ned i mekanikken, blir det lettere å vurdere hva som er mulig nå og <a href="https://www.datatilsynet.no/regelverk-og-verktoy/sporsmal-svar/sandkasse-for-kunstig-intelligens/" target="_blank" rel="noopener noreferrer">hvor risikoen ligger</a>. Da kan norske bedrifter bruke AI der det gir ekte verdi, og la resten ligge til verktøyene, dataene og rutinene er modne nok.</p>
<h2>KI bruksområder og eksempler</h2>
<p>Det er nyttig å forstå hvordan maskinlæringsløpet henger sammen fra data til drift. Verdien blir likevel tydeligst når vi ser hvordan norske virksomheter bruker metodene på ekte problemer. Når modeller får rene data, gode algoritmer og en trygg vei ut i produksjon, skjer det noe konkret i møte med kunder og brukere. Derfor er eksemplene under interessante. De viser både bredden i bruksområder og hva som må være på plass for at nytten skal skalere.</p>
<h3>Helse</h3>
<p>Sykehus håndterer store mengder bilde og tekst. Flere norske fagmiljøer har begynt å ta i bruk modeller som hjelper radiologer med å prioritere, og som kan peke ut funn som bør sees først. Prinsippet er enkelt. Bilder kvalitetssikres og normaliseres før treningen, deretter lærer nevrale nettverk å kjenne igjen mønstre som er vanskelige å se med det blotte øye. I klinisk bruk skal modellen aldri stå alene. Den fungerer som en ekstra leser som reduserer ventetid og frigjør tid til de mest krevende vurderingene. Når datasett er kuratert og rutiner for kvalitet og personvern er på plass, kan slike systemer gi raskere og jevnere pasientflyt.</p>
<h3>Handel</h3>
<p>Anbefalingsmotorer er blitt en del av infrastrukturen i norsk netthandel. Aktører innen dagligvare, elektronikk og sport bruker kombinasjoner av kollaborativ filtrering og innholdsbaserte modeller for å foreslå relevante produkter i sanntid. Modellen ser på hva lignende kunder faktisk gjør, ikke bare hva de sier at de liker. Den lærer av klikk, kjøp og kontekst, og den tester små varianter hele tiden. Resultatet er startflater som føles mer personlige, epost som oppleves nyttige, og produktlister som prioriterer smartere. Felles for de som lykkes, er at de kobler algoritmene tett på lager, pris og kampanje, slik at anbefalingene speiler reell tilgjengelighet og margin.</p>
<figure><img src="/posts/hvordan-ki-egentlig-virker/3.jpg" alt="Hvordan KI egentlig virker" loading="lazy" /></figure>
<h3>Finans</h3>
<p>Bank og betaling er naturgitte hjemmebaner for maskinlæring. Norske finansmiljøer bruker modeller som analyserer transaksjoner i millisekunder for å fange opp uvanlige mønstre. Gradvis boosting og dype nettverk kombineres for å øke treffsikkerheten uten å plage ærlige kunder. Systemene flagger de mest risikable hendelsene automatisk og sender gråsonene til menneskelig vurdering. Dermed holdes svindeltrykket nede, samtidig som friksjonen for betaleren forblir lav. Det som skiller de beste, er disiplin i etterkontroll og løpende læring fra bekreftede saker, slik at modellen forbedres uten å lære feil.</p>
<h3>Språk og kommunikasjon</h3>
<p>Norske virksomheter sitter på store mengder ustrukturert tekst. Med moderne transformermodeller kan kundeservice få sammendrag av lange henvendelser på et blunk, og redaksjoner kan få forslag til metadata og titler som faktisk matches mot innholdet. Nøkkelen er solide treningskorpus og målrettet finjustering mot domenet. Når språket er norsk, blir datakvalitet ekstra viktig. Feil i segmentering eller oversettelser forplanter seg raskt til brukeropplevelsen. Derfor kombinerer mange automatiserte forslag med menneskelig kvalitetskontroll før publisering.</p>
<h3>Logistikk</h3>
<p>Ruteplanlegging og kapasitetsstyring er klassiske optimaliseringsproblemer. Norske logistikkaktører bruker maskinlæring og operasjonsanalyse side om side for å legge smartere ruter og planlegge bemanning. Input kommer fra historikk, trafikkdata og geografi. Modellene vurderer løpende hva som er raskest og mest robust, og de foreslår endringer når forholdene endrer seg. Effekten merkes i drivstofforbruk, leveringspresisjon og kundetilfredshet. Det fungerer fordi innsikten er tett integrert i den daglige arbeidsflyten og fordi sjåfører og planleggere får verktøy som er enkle å bruke.</p>
<figure><img src="/posts/hvordan-ki-egentlig-virker/4.jpg" alt="Hvordan KI egentlig virker" loading="lazy" /></figure>
<p>For å oppsummere bygger alle disse løsningene på samme kjede. Relevante og godt rensede data legges til grunn. Algoritmene velges med utgangspunkt i problemet, ikke trenden. Modeller trenes, valideres og styres inn i drift på en kontrollert måte. Deretter overvåkes de og forbedres når virkeligheten endrer seg. Det er ikke bare suksesshistorier, det er håndverk som gjør at maskinlæring blir til målbar verdi i den virkelige verden.</p>`,
}
